name: Validate PR Diff in Salesforce

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v2

      - name: Authenticate with Salesforce (Auth URL)
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias targetOrg
          sf org display --target-org targetOrg

      - name: Get changed metadata files
        id: diff
        run: |
          git fetch origin ${{ github.base_ref }}
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep 'force-app' || true)
          echo "CHANGED_FILES=$FILES" >> $GITHUB_ENV

      - name: Show changed files
        run: |
          echo "Changed files:"
          echo "$CHANGED_FILES"

      - name: Validate deployment of changed files
        if: env.CHANGED_FILES != ''
        run: |
          echo "$CHANGED_FILES" | tr ' ' '\n' > changed-files.txt
          echo "Deploying validation only for:"
          cat changed-files.txt
          sf project deploy start \
            --source-path $(cat changed-files.txt | tr '\n' ',') \
            --target-org targetOrg \
            --ignore-conflicts \
            --test-level RunLocalTests \
            --dry-run \
            --wait 30
