name: Delta Deployment
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  delta-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global 

      - name: Install sfdx-git-delta
        run: sf plugins install sfdx-git-delta

      - name: Authenticate with Salesforce
        env:
          SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
        run: |
          echo "Authenticating to Salesforce dev hub using auth URL..."
          sf org login sfdx-url --sfdx-url-file <(echo "$SF_AUTH_URL") --set-default-dev-hub --set-default 

      - name: Authenticate with Salesforce Sandbox
        env:
          SANDBOX_NAME: ${{ github.event.inputs.sandboxName }}
        run: |
          echo "Authenticating to Salesforce dev hub using auth URL..."
          sf org resume sandbox --name=$SANDBOX_NAME

      - name: Generate delta package
        run: |
          MERGE_BASE=$(git merge-base ${{ github.base_ref }} ${{ github.head_ref }})
          sf sgd source delta --from $MERGE_BASE --to ${{ github.head_ref }} --ignore-whitespace

      - name: Deploy delta to org
        env:
          SANDBOX_NAME: ${{ github.event.inputs.sandboxName }}
          SF_USER:  ${{ secrets.SF_USER }}
        run: sf project deploy start -o $SF_USER.$SANDBOX_NAME -x output/package.xml --checkonly
