name: PMD Validation

on:
  pull_request:
    branches:
      - dev

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Download PMD
        run: |
          curl -L https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.16.0/pmd-dist-7.16.0-bin.zip -o pmd.zip
          unzip -q pmd.zip
          mv pmd-bin-7.16.0 pmd

      - name: Run PMD
        run: |
          ./pmd/bin/pmd check \
            --dir . \
            --rulesets .github/rulesets/salesforce-ruleset.xml \
            --report-file pmd-report.sarif \
            --format sarif

      - name: Upload SARIF results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif

      - name: Comment on PR with non-inline PMD violations
        if: ${{ github.event.pull_request.base.ref == 'dev' }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const sarif = JSON.parse(fs.readFileSync('pmd-report.sarif', 'utf8'));

            const results = sarif.runs?.[0]?.results || [];
            if (results.length === 0) return;

            const otherFindings = [];
            for (const r of results) {
              const loc = r.locations?.[0]?.physicalLocation;
              if (!loc) continue;
              const file = loc.artifactLocation?.uri || '';
              const startLine = loc.region?.startLine || '';
              const msg = r.message?.text || 'Violation';
              otherFindings.push(`- **${file}:${startLine}** — ${msg}`);
            }

            if (otherFindings.length > 0) {
              const body = `
              ### ⚠️ Additional PMD Violations Found

              Inline annotations are shown in the PR diff only for changed lines.  
              The following violations were found in files you modified, but not on changed lines:

              ${otherFindings.join('\n')}

              👉 Reviewers: [View full Code Scanning alerts tab](${context.payload.pull_request.html_url.replace('/pull/', '/security/code-scanning?query=is:open')})
              `;

              // Delete old bot comments first (so it doesn’t spam multiple)
              const { data: comments } = await github.rest.issues.listComments({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });

              const existing = comments.find(c =>
                c.user.type === "Bot" &&
                c.body.includes("### ⚠️ Additional PMD Violations Found")
              );

              if (existing) {
                await github.rest.issues.updateComment({
                  comment_id: existing.id,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body,
                });
              } else {
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body,
                });
              }
            }
