name: Scrambled Named Credentials

on:
  workflow_dispatch: # run manually

jobs:
  update-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      # Step 2: Install and set up the Salesforce CLI.
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global

      - name: Authenticate with Salesforce
        env:
          SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
        run: |
          echo "Authenticating to Salesforce dev hub using auth URL..."
          sf org login sfdx-url --sfdx-url-file <(echo "$SF_AUTH_URL") --set-default-dev-hub --set-default 

      - name: Authenticate with Salesforce Sandbox
        env:
          SANDBOX_NAME: ${{ github.event.inputs.sandboxName }}
        run: |
          echo "Authenticating to Salesforce dev hub using auth URL..."
          sf org resume sandbox --name=$SANDBOX_NAME

      - name: Run XML update script
        run: scripts/bash/update_named_creds.sh

      - name: Initiate SFDMU job
        env:
          SANDBOX_NAME: ${{ github.event.inputs.sandboxName }}
          SF_USER:  ${{ secrets.SF_USER }}
        run: |
          echo "Querying for sandbox: $SANDBOX_NAME"
          sf project deploy start -o $SF_USER.$SANDBOX_NAME -m NamedCredential --dry-run  
